[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/api/submit"
  to = "/.netlify/functions/submit"
  status = 200

[[redirects]]
  from = "/api/settings"
  to = "/.netlify/functions/settings"
  status = 200
